apiVersion: batch/v1
kind: CronJob
metadata:
  name: cristal-crawler
spec:
  schedule: "0 3 * * 0"  # Domingos às 3h
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: crawler
              image: cristal:latest
              command:
                - python
                - -m
                - app.adapters.inbound.cli.crawler
                - --update
              envFrom:
                - configMapRef:
                    name: cristal-config
                - secretRef:
                    name: cristal-secrets
          restartPolicy: OnFailure
